In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error
from tensorflow import keras
from tensorflow.keras import layers
import ast  # Library for handling literal_eval
from geopy.distance import geodesic

In [2]:
# !pip install geopy

In [3]:
df = pd.read_csv('merged.csv')

In [4]:
df

Main_Category  Longitude  Latitude  Day   duration  Primary_Vehicle   
0                  1    151.058  -33.9431    5  39.319950                1  \
1                  0    151.159  -33.8096    6  12.029000                1   
2                  1    150.875  -33.7344    6  16.956667                1   
3                  1    150.973  -33.8172    6  42.804117                5   
4                  1    150.981  -33.7919    6  40.840000                3   
...              ...        ...       ...  ...        ...              ...   
85606              0    151.193  -33.8877    5   0.073550                1   
85607              1    151.054  -33.7991    6   0.000000                6   
85608              1    151.066  -33.7527    6   0.000000                3   
85609              0    151.154  -33.7587    6   0.000000                5   
85610              0    151.196  -33.9220    6   0.000000                0   

       Secondary_Vehicle  Is_Major_Incident  Advice_A  Advice_B  ...   
0                      2                  0        10         0  ...  \
1                      9                  0        10       134  ...   
2                      9                  0        26       134  ...   
3                      2                  0        10         0  ...   
4                      4                  0        10       134  ...   
...                  ...                ...       ...       ...  ...   
85606                  8                  0        26       134  ...   
85607                  8                  0        26       134  ...   
85608                  8                  0         3       134  ...   
85609                  8                  0         3       134  ...   
85610                  8                  0        10        14  ...   

       Motorway Crew  Tow Truck  Transport for NSW  RMS  Emergency services   
0                  0          0                  0    0                   1  \
1                  1          0                  0    0                   0   
2                  1          0                  0    0                   1   
3                  0          0                  1    0                   1   
4                  0          1                  0    0                   0   
...              ...        ...                ...  ...                 ...   
85606              0          0                  0    1                   0   
85607              0          0                  0    1                   0   
85608              0          0                  0    0                   0   
85609              0          0                  0    1                   0   
85610              0          0                  0    1                   0   

       Incident_Type  Num_Vehicles_Involved  Month  Hour  distance_to_CBD  
0                  0                      2      8    19        15.781064  
1                  1                      1      8     0         8.323913  
2                  0                      1      8     1        34.354983  
3                  0                      1      8     1        22.500677  
4                  0                      3      8     1        22.753003  
...              ...                    ...    ...   ...              ...  
85606              1                      1      8     8         2.041047  
85607              0                      2      8     4        16.348803  
85608              0                      3      8     4        18.664398  
85609              1                      1      8     4        13.608235  
85610              1                      1      8     4         5.496973  

[85611 rows x 83 columns]

In [5]:
df.head(3).T

0           1           2
Main_Category            1.000000    0.000000    1.000000
Longitude              151.058000  151.159000  150.875000
Latitude               -33.943100  -33.809600  -33.734400
Day                      5.000000    6.000000    6.000000
duration                39.319950   12.029000   16.956667
...                           ...         ...         ...
Incident_Type            0.000000    1.000000    0.000000
Num_Vehicles_Involved    2.000000    1.000000    1.000000
Month                    8.000000    8.000000    8.000000
Hour                    19.000000    0.000000    1.000000
distance_to_CBD         15.781064    8.323913   34.354983

[83 rows x 3 columns]

In [6]:
# Print the column names to verify
print(df.columns)

Index(['Main_Category', 'Longitude', 'Latitude', 'Day', 'duration',
       'Primary_Vehicle', 'Secondary_Vehicle', 'Is_Major_Incident', 'Advice_A',
       'Advice_B', 'Closure_Type', 'Direction', 'Main_Street',
       'Affected_Lanes', 'Actual_Number_of_Lanes ', 'Suburb', 'Traffic_Volume',
       'SA2_CODE21', 'SA3_CODE21', 'SA3_NAME21', 'SA4_CODE21', 'SA4_NAME21',
       'AREASQKM21', '1_Area', '2_ML', '3_TRL', '4_PRL', '5_SRL', '6_TrRL',
       '7_RRL', '8_LsRL', '9_URL', '10_ToRL', '11_EoR', '12_NoN', '13_NDEs',
       '14_NNC2L', '15_NNC3L', '16_NNC4L', '17_AND', '18_NE', '19_MCI',
       '20_CoI', '21 NBS', '22_CA', '23_EA', '24_HA', '25_IA', '26_OA',
       '27_PA', '28_PrA', '29_RA', '30_TA', '31_WbA', '32_EoLU', '33_TP',
       '34_PD0MV', '35_PD1MV', '36_PD2MV', '37_PD3MV', '38_PD≥4MV', '39_PUE',
       '40_AMI', '41_NPTtWbyPT', '42_NPTtWbyTx', '43_NPTtWbyCD',
       '44_NPTtWbyCP', '45_NPTtWbyO', '46_NPWfH', '47_PWCJH', '48_PBCJH',
       '49_ANP_FH', 'Emergency service(s)', 

## prepare classifier

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
import lightgbm as lgb




names = [
    "Nearest Neighbors",
    "XGBoost",
    "LightGBM",
]

classifiers = [
    KNeighborsClassifier(3),
    xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42),
    lgb.LGBMClassifier(random_state=42),
]


C:\Python3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


## prepare data

In [8]:
# Handle missing values, if any
df = df.dropna()

# Split data into features (X) and target (y)
X = df.drop(['Longitude', 'Latitude','duration'] , axis=1)
y = df['duration']

y = (df['duration'] > 45).astype(int)  # Target variable (1 if duration is long, 0 if short)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## modeling

In [9]:
for name, clf in zip(names, classifiers):
    # Train the classifier
    clf.fit(X_train, y_train)

    # Predictions on the test set
    y_pred = clf.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)

    # Cross-validated accuracy
    cross_val_acc = cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy').mean()

    # Display the results
    print(f'Model: {name}')
    print(f'Accuracy: {accuracy:.2f}')
    print(f'Confusion Matrix:\n{conf_matrix}')
    print(f'Classification Report:\n{classification_rep}')
    print(f'Cross-validated Accuracy: {cross_val_acc:.2f}')
    print('===============================================')

Model: Nearest Neighbors
Accuracy: 0.67
Confusion Matrix:
[[9461 2084]
 [3339 1676]]
Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.82      0.78     11545
           1       0.45      0.33      0.38      5015

    accuracy                           0.67     16560
   macro avg       0.59      0.58      0.58     16560
weighted avg       0.65      0.67      0.66     16560

Cross-validated Accuracy: 0.67


C:\Python3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Python3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Python3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Python3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")
C:\Python3\lib\site-packages\xgboost\sklearn.py:1395: UserWarning: `use_label_encoder` is deprecated in 1.7.0.
  warnings.warn("`use_label_encoder` is deprecated in 1.7.0.")


Model: XGBoost
Accuracy: 0.73
Confusion Matrix:
[[10332  1213]
 [ 3241  1774]]
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.89      0.82     11545
           1       0.59      0.35      0.44      5015

    accuracy                           0.73     16560
   macro avg       0.68      0.62      0.63     16560
weighted avg       0.71      0.73      0.71     16560

Cross-validated Accuracy: 0.73
Model: LightGBM
Accuracy: 0.73
Confusion Matrix:
[[10567   978]
 [ 3424  1591]]
Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.92      0.83     11545
           1       0.62      0.32      0.42      5015

    accuracy                           0.73     16560
   macro avg       0.69      0.62      0.62     16560
weighted avg       0.71      0.73      0.70     16560

Cross-validated Accuracy: 0.74
